// IPC Event Constants
const IPC_EVENTS = {
	// Recording
	RECORDING_STATUS_CHANGED: "RECORDING_STATUS_CHANGED",
	RECORDING_STATUS_UPDATE: "RECORDING_STATUS_UPDATE",
	START_RECORDING: "START_RECORDING",
	STOP_RECORDING: "STOP_RECORDING",
	RECORDING_ERROR: "RECORDING_ERROR",
	RECORDING_PROGRESS: "RECORDING_PROGRESS",
	UPDATE_RECORDING_SOURCE: "UPDATE_RECORDING_SOURCE",
	UPDATE_RECORDING_DELAY: "UPDATE_RECORDING_DELAY",

	// Media Streaming
	START_MEDIA_STREAM: "START_MEDIA_STREAM",
	WRITE_MEDIA_CHUNK: "WRITE_MEDIA_CHUNK",
	END_MEDIA_STREAM: "END_MEDIA_STREAM",

	// Editor
	EDITOR_CLOSED: "EDITOR_CLOSED",
	CLOSE_EDITOR_WINDOW: "CLOSE_EDITOR_WINDOW",
	EDITOR_LOAD_ERROR: "EDITOR_LOAD_ERROR",
	START_EDITING: "START_EDITING",
	PROCESSING_COMPLETE: "PROCESSING_COMPLETE",

	// Media State
	GET_MEDIA_STATE: "GET_MEDIA_STATE",
	MEDIA_STATE_UPDATE: "MEDIA_STATE_UPDATE",
	MEDIA_READY: "MEDIA_READY",
	MEDIA_ERROR: "MEDIA_ERROR",
	GET_MEDIA_PATHS: "GET_MEDIA_PATHS",
	MEDIA_PATHS: "MEDIA_PATHS",

	// Camera
	CAMERA_DEVICE_CHANGED: "CAMERA_DEVICE_CHANGED",
	CAMERA_STATUS_CHANGED: "CAMERA_STATUS_CHANGED",
	START_CAMERA: "START_CAMERA",
	STOP_CAMERA: "STOP_CAMERA",

	// Audio
	AUDIO_DEVICE_CHANGED: "AUDIO_DEVICE_CHANGED",
	AUDIO_STATUS_CHANGED: "AUDIO_STATUS_CHANGED",

	// Area Selection
	START_AREA_SELECTION: "START_AREA_SELECTION",
	AREA_SELECTED: "AREA_SELECTED",
	UPDATE_SELECTED_AREA: "UPDATE_SELECTED_AREA",
	GET_CROP_INFO: "GET_CROP_INFO",

	// Window Management
	WINDOW_CLOSE: "WINDOW_CLOSE",
	START_WINDOW_DRAG: "START_WINDOW_DRAG",
	WINDOW_DRAGGING: "WINDOW_DRAGGING",
	END_WINDOW_DRAG: "END_WINDOW_DRAG",
	GET_WINDOW_POSITION: "GET_WINDOW_POSITION",
	UPDATE_WINDOW_SIZE: "UPDATE_WINDOW_SIZE",

	// File Operations
	SAVE_TEMP_VIDEO: "SAVE_TEMP_VIDEO",
	SHOW_SAVE_DIALOG: "SHOW_SAVE_DIALOG",
	READ_VIDEO_FILE: "READ_VIDEO_FILE",
	SAVE_VIDEO_FILE: "SAVE_VIDEO_FILE",
	SAVE_CANVAS_RECORDING: "SAVE_CANVAS_RECORDING",

	// Desktop Capturer
	DESKTOP_CAPTURER_GET_SOURCES: "DESKTOP_CAPTURER_GET_SOURCES",

	// Reset
	RESET_FOR_NEW_RECORDING: "RESET_FOR_NEW_RECORDING",

	// Audio Settings
	UPDATE_AUDIO_SETTINGS: "UPDATE_AUDIO_SETTINGS",
	AUDIO_SETTINGS_UPDATED: "AUDIO_SETTINGS_UPDATED",
	GET_AUDIO_SETTINGS: "GET_AUDIO_SETTINGS",

	// Mouse Position
	MOUSE_POSITION_UPDATED: "MOUSE_POSITION_UPDATED",

	// Recording Delay
	GET_RECORDING_DELAY: "GET_RECORDING_DELAY",

	// Load Cursor Data
	LOAD_CURSOR_DATA: "LOAD_CURSOR_DATA",

	// Editor Settings
	UPDATE_EDITOR_SETTINGS: "UPDATE_EDITOR_SETTINGS",
	GET_EDITOR_SETTINGS: "GET_EDITOR_SETTINGS",

	// Save Screenshot
	SAVE_SCREENSHOT: "SAVE_SCREENSHOT",

	// Permissions
	CHECK_PERMISSIONS: "CHECK_PERMISSIONS",

	// File Protection
	PROTECT_FILE: "PROTECT_FILE",
	UNPROTECT_FILE: "UNPROTECT_FILE",
	GET_PROTECTED_FILES: "GET_PROTECTED_FILES",
};

module.exports = {
	IPC_EVENTS,
};
